[정렬, 맵, 셋] 2월 20일
Altu-Bitu-6/Altu-Bitu-JoYudam pull request #1
Opened 2024-02-20 08:16 UTC by youdame

### 인적사항
학번 : 1942501 
이름 : 조유담

### 과제제출
기존제출 : 1431, 19636, 14425

2024-02-21 15:12 UTC, kimhj010502 reviewed
**[정렬, 맵, 셋 구현 문제 코드 리뷰 완료]**

19636(P2)

유담님 안녕하세요!
과제하시느라 수고 많으셨습니다!! 어려운 문제인데도 잘 풀어주셨네요! 🥰 
코드에 대한 주석도 너무 좋았습니다 👍
몇 가지 사소한 코멘트 드렸습니다.
궁금한 점이 있으면 리뷰어를 호출해주세요!

2024-02-21 15:12 UTC, kimhj010502 commented on 01_정렬_맵_셋/필수/19636.cpp
> +int main() {
P2. 모든 연산을 main 함수에서 해주었네요~ 알튜비튜에서는 함수로 구현할 수 있는 부분은 최대한 함수를 따로 정의해서 사용하는 것을 권장하고 있어요! 다음부터는 함수화할 수 있는 부분이 있을지 고려해주세요!

2024-02-21 15:12 UTC, kimhj010502 commented on 01_정렬_맵_셋/필수/19636.cpp
> +    cin >> D >> I >> A;
P2. 변수 이름은 스네이크 표기법으로 작성해주세요!

2024-02-21 15:12 UTC, kimhj010502 commented on 01_정렬_맵_셋/필수/19636.cpp
> +        }
복잡한 연산을 잘 구현해주셨네요~👍

2024-02-23 11:19 UTC, chae-jpg requested changes
**[정렬, 맵, 셋 이론 코드리뷰 완료]**

1431(P3), 14425(P1)
유담님 안녕하세요! 코드 리뷰 완료되었습니다👍
14425번 문제가 현재 백준에서 오답 판정이 나오고 있어 제출로 인정되지 못했습니다 😢 코멘트 확인해주시고, 수정해주시면 바로 확인 후 제출로 인정해드리겠습니다!
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-02-23 11:19 UTC, chae-jpg commented on 01_정렬_맵_셋/필수/1431.cpp
> +bool compareSerials(string a, string b) {
사용자 정의 정렬을 위해서 비교 함수를 잘 선언해주셨네요!

2024-02-23 11:19 UTC, chae-jpg commented on 01_정렬_맵_셋/필수/14425.cpp
> +    int N;
P3
알튜비튜에서는 전역변수를 제외하고는 변수명에 대문자 사용을 지양하고 있어요.
n과 같은 이름으로 변경하면 더 좋을 것 같아요!

2024-02-23 11:19 UTC, chae-jpg commented on 01_정렬_맵_셋/필수/14425.cpp
> +                cout << K << std::endl;
P1
문제에서는 전체 개수만 출력하기를 요구하고 있기 때문에, 일치하는 문자열의 출력은 필요하지 않습니다!

2024-02-23 11:19 UTC, chae-jpg commented on 01_정렬_맵_셋/필수/14425.cpp
> +            }
P1
이 부분에서 선형탐색을 하면 시간복잡도가 O(N^2)가 되고, 따라서 시간 초과 판정이 나오고 있어요! 😢
수업시간에 배운 더 빠른 탐색이 가능한 컨테이너가 있었죠? 그 자료구조를 사용해볼까요?

2024-02-27 03:14 UTC, youdame commented on 01_정렬_맵_셋/필수/1431.cpp
> +bool compareSerials(string a, string b) {
@chae-jpg 안녕하세요 늦게 언급드려서 죄송합니다 ㅠㅠ 리뷰 반영했으니, 확인 부탁드립니다!

2024-02-28 03:03 UTC, chae-jpg commented on 01_정렬_맵_셋/필수/1431.cpp
> +bool compareSerials(string a, string b) {
@youdame 안녕하세요! 14425번 파일에 19636번 코드가 들어간 것 같습니다ㅜㅜ 다시 확인해보시겠어요?

2024-03-05 06:11 UTC, merged